# Generated by Django 5.0.6 on 2024-06-06 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Оборудование/Прибор КИПиА')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Модель оборудования')),
            ],
            options={
                'verbose_name_plural': 'Модели оборудования',
            },
        ),
        migrations.CreateModel(
            name='EquipmentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование оборудования')),
            ],
            options={
                'verbose_name_plural': 'Наименование оборудования',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name_plural': 'Типы оборудования',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Производитель оборудования')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=25, verbose_name='Серийный номер')),
                ('at_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='device.category', verbose_name='Категория')),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='model', to='device.equipmentmodel')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='n', to='device.equipmentname')),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='t', to='device.equipmenttype')),
                ('manufacturer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manufacturer', to='device.manufacturer')),
            ],
            options={
                'verbose_name_plural': 'Оборудование',
                'ordering': ('-at_date',),
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Описание ')),
                ('at_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Кто внес данные')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='descriptions', to='device.equipment')),
            ],
            options={
                'verbose_name_plural': 'Описания',
                'ordering': ('-at_date',),
            },
        ),
        migrations.CreateModel(
            name='DefectAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Номер деффектного акта')),
                ('defect_act', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='acts', to='device.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='DateCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateField(verbose_name='Дата внесения записи деффекта')),
                ('date_create', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='createds', to='device.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ФИО подряднчика')),
                ('job_title', models.CharField(max_length=50, verbose_name='Должность')),
                ('organization', models.CharField(max_length=100, verbose_name='Организация')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contractors', to='device.equipment')),
            ],
            options={
                'verbose_name_plural': 'Подрядные организации',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Свидетельство о поверке')),
                ('at_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Кто внес данные')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='certificates', to='device.equipment')),
            ],
            options={
                'verbose_name_plural': 'Свидетельства о поверке',
                'ordering': ('-at_date',),
            },
        ),
        migrations.CreateModel(
            name='Causes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Причина оказа')),
                ('causes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='causes', to='device.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Approve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ФИО утв.')),
                ('job_title', models.CharField(max_length=50, verbose_name='Должность')),
                ('organization', models.CharField(max_length=100, verbose_name='Организация')),
                ('approve', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approves', to='device.equipment')),
            ],
            options={
                'verbose_name_plural': 'Утверждающие',
            },
        ),
        migrations.CreateModel(
            name='Fix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Что требуется для устранения')),
                ('fix', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixes', to='device.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='InvestLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Номер письма в Инвест')),
                ('invest_letter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invest_letters', to='device.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Kait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ФИО мастера Каит')),
                ('job_title', models.CharField(max_length=50, verbose_name='Должность')),
                ('organization', models.CharField(max_length=100, verbose_name='Организация')),
                ('kait', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='kaits', to='device.equipment')),
            ],
            options={
                'verbose_name_plural': 'Мастера КАиТ',
                'ordering': ('-job_title',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Место установки')),
                ('at_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='locations', to='device.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Кто внес данные')),
            ],
            options={
                'verbose_name_plural': 'Места установки',
                'ordering': ('-at_date',),
            },
        ),
        migrations.CreateModel(
            name='OperatingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SmallIntegerField(verbose_name='Время наработки')),
                ('operating_time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operating_times', to='device.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер по генплану')),
                ('construction', models.CharField(blank=True, max_length=100, verbose_name='Наименование здания, сооружения')),
                ('at_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='positions', to='device.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Кто внес данные')),
            ],
            options={
                'verbose_name_plural': 'Позиции',
                'ordering': ('-number',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование проекта')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project', to='device.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='RealLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Действительное место нахождения')),
                ('at_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reallocations', to='device.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Кто внес данные')),
            ],
            options={
                'verbose_name_plural': 'Действительное место нахождения',
                'ordering': ('-at_date',),
            },
        ),
        migrations.CreateModel(
            name='ShortDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Краткое описание деффекта')),
                ('short_description', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='short_descriptions', to='device.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('rem', 'снят'), ('inst', 'установлен'), ('in_v', 'в поверку'), ('from_v', 'с поверки'), ('rep', 'ремонт'), ('def', 'дефектован')], default='inst', max_length=25, verbose_name='Статус')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status', to='device.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тэг')),
                ('at_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('tag_d', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tags', to='device.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Кто внес данные')),
            ],
            options={
                'verbose_name_plural': 'Тэги',
                'ordering': ('-at_date',),
            },
        ),
        migrations.CreateModel(
            name='VerificationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_verification', models.DateField(verbose_name='Дата предыдущей поверки')),
                ('next_verification', models.DateField(verbose_name='Дата следующей поверки')),
                ('at_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Кто внес данные')),
                ('verification_date', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='verifications', to='device.equipment')),
            ],
            options={
                'verbose_name_plural': 'Даты поверок',
                'ordering': ('-at_date',),
            },
        ),
        migrations.CreateModel(
            name='VerificationInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SmallIntegerField(verbose_name='Межповерочный интервал')),
                ('interval', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='interval', to='device.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ФИО мастера цеха')),
                ('job_title', models.CharField(max_length=100, verbose_name='Должность')),
                ('organization', models.CharField(max_length=100, verbose_name='Организация')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workers', to='device.equipment')),
            ],
            options={
                'verbose_name_plural': 'Мастера цеха',
            },
        ),
    ]
