# Generated by Django 5.0.6 on 2024-09-10 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_draft', models.CharField(max_length=150, verbose_name='Место установки')),
                ('tag_draft', models.CharField(max_length=150, verbose_name='Тэг')),
                ('description_draft', models.CharField(max_length=150, verbose_name='Описание')),
                ('images', models.ImageField(upload_to='images', verbose_name='Фото')),
                ('poz_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.gp', verbose_name='Поз. по ГП')),
                ('status_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.statusadd', verbose_name='Статус')),
                ('user_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
