# Generated by Django 4.2 on 2024-09-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_remove_si_error_device_delete_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='max_scale',
            field=models.CharField(max_length=10, verbose_name='Максимум шкалы'),
        ),
        migrations.AlterField(
            model_name='scale',
            name='min_scale',
            field=models.CharField(max_length=10, verbose_name='Минимум шкалы'),
        ),
    ]
