# Generated by Django 4.2 on 2024-09-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_alter_scale_max_scale_alter_scale_min_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Единицы измерения'),
        ),
    ]
