# Generated by Django 4.2 on 2024-09-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_alter_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Модель оборудования'),
        ),
    ]
