# Generated by Django 4.2 on 2024-09-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_alter_equipmentmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentname',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование оборудования'),
        ),
    ]
