# Generated by Django 4.2 on 2024-09-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_alter_equipmentname_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Тип оборудования'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место нахождения.'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Производитель оборудования'),
        ),
    ]
