# Generated by Django 4.2 on 2024-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_alter_equipmenttype_name_alter_location_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(blank=True, null=True, verbose_name='Позиция по ГП'),
        ),
    ]
