name: Тестирование и развертывание проекта

on:
  push:
    branches:
      - main


jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      DEBUG: ${{secrets.DEBUG}}
      ALLOWED_HOSTS: ${{secrets.ALLOWED_HOSTS}}
      DB_ENGINE: ${{secrets.DB_ENGINE}}
      DB_NAME: ${{secrets.DB_NAME}}
      DB_USER: ${{secrets.DB_USER}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_HOST: ${{secrets.DB_HOST}}
      DB_PORT: ${{secrets.DB_PORT}}
    services:
      postgres_main:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: ${{env.DB_PASSWORD}}
          POSTGRES_USER: ${{env.DB_USER}}
          POSTGRES_DB: ${{env.DB_NAME}}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
      #        with:
      #          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Деплой
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_KEY }}
          script: |
            cd /home/admin/kip/stock/equipment
            git pull origin main
            source env/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            sudo systemctl restart gunicorn
            
        #      - name: Тестирование
        #        run: python manage.py test
        env:
          SECRET_KEY: ${{env.SECRET_KEY}}
          DEBUG: ${{env.DEBUG}}
          ALLOWED_HOSTS: ${{env.ALLOWED_HOSTS}}
          DB_ENGINE: ${{env.DB_ENGINE}}
          DB_NAME: ${{env.DB_NAME}}
          DB_USER: ${{env.DB_USER}}
          DB_PASSWORD: ${{env.DB_PASSWORD}}
          DB_HOST: ${{env.DB_HOST}}
          DB_PORT: ${{env.DB_PORT}}


